distribution_code_name: "emacs-rime"
distribution_name: Rime
distribution_version: 1.0.1
install_time: "Mon Aug 17 16:14:16 2020"
installation_id: "b5446d7d-fbde-4dff-adc3-903e338ebd7b"
rime_version: 1.7.3
update_time: "Sun Apr 25 21:08:52 2021"